### ISSUE TITLE
User can add photos to their inspiration board

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/final-project#1]
## ⚙️ Feature

User can add photos to their inspiration board

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on an icon to add photos and it will open their Finder/Explorer to allow them to upload photos to a database

## 🖼️ Wireframes

<img width="232" alt="Screen Shot 2021-05-26 at 3 39 51 PM" src="https://user-images.githubusercontent.com/74742148/119740390-b2137e00-be38-11eb-873b-337ea9f65fbb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### Setup
- [x] Install `multer` as a dependency
- [x] Make a copy of .env.example

### 🐘 Database

- [x] Update `schema.sql` to create an images table with URL and imageId

### ☁️ Server

- [x] Create an uploadsMiddleware
- [x] Update `server/index.js` to include a post request to add a new image to the database
- [x] Test with HTTPie
- [x] Update `server/index.js` to include a get request for all images in database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a static component to display inspiration board
- [x] Create a static component to handle uploads
- [x] Create a static component for where images will eventually go
- [x] Make UploadPhotos a dynamic component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
