### ISSUE TITLE
User can add guests to guest list

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/final-project#3]
## ⚙️ Feature

User can add guests to guest list

## 📐 Functionality

User can click on add guest at the bottom of the page Guest List page. Clicking on add guest will open a modal with a form to add guest's first and last name and then save the added guest to their list

## 🖼️ Wireframes

<img width="328" alt="Screen Shot 2021-05-27 at 11 57 09 PM" src="https://user-images.githubusercontent.com/74742148/119942971-423fe900-bf47-11eb-9c83-3ab3f555cada.png">
<img width="322" alt="Screen Shot 2021-05-27 at 11 59 11 PM" src="https://user-images.githubusercontent.com/74742148/119943180-892dde80-bf47-11eb-96e9-c6e3716340f6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add a new table "Guests" with firstName, lastName, guestId

### ☁️ Server

- [x] Update `server/index.js` to include POST request to add new guest
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a new Guest List page
- [x] Create Header component
- [x] Create a static footer component 
- [x] Update footer component to handle click event for adding new guest
- [x] Create a modal form to add new guest
- [x] Update component to open and close modal with event listeners
- [x] Create post request when user submits a new guest's information

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
