### ISSUE TITLE
User can update status for each guest

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/final-project#4]
## ⚙️ Feature

User can update status for each guest

## 📐 Functionality

When the user clicks "Add Guest", an "add guest" modal opens to add the guest's first name, last name, and status.

## 🖼️ Wireframes

<img width="334" alt="Screen Shot 2021-05-30 at 10 11 15 PM" src="https://user-images.githubusercontent.com/74742148/120142889-f46bf080-c193-11eb-8152-c3df4fe23381.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include status column in guests table

### ☁️ Server

- [x] Update `server/index.js` to include status in post request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update GuestForm component to have a radio input
- [x] Style radio input
- [x] Test functionality

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
