### ISSUE TITLE
User can create and update account information

### ISSUE THREAD

**Issue by NatalieNunez** [NatalieNunez/final-project#5]
## ⚙️ Feature

User can create and update account information

## 📐 Functionality

While on the profile page, if the user clicks the Edit button, they are able to edit their information and save once done making changes.

## 🖼️ Wireframes
<img width="267" alt="Screen Shot 2021-06-01 at 12 57 54 AM" src="https://user-images.githubusercontent.com/74742148/120287832-77fd0e80-c274-11eb-97d7-67c0551b60b9.png">
<img width="295" alt="Screen Shot 2021-06-01 at 12 59 32 AM" src="https://user-images.githubusercontent.com/74742148/120287999-a11d9f00-c274-11eb-829c-4ea9c3ff08dd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a table named "Users" with a "userId", "userName", "partnerName" and "weddingDate" columns
- [x] Update `data.sql` to have a User 1 added to "Users"

### ☁️ Server

- [x] Update `server/index.js` to include a PUT request for changing information of user's profile
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Profile page
- [x] Create a ProfileForm component
- [x] Update ProfileForm to have a PUT request
- [x] Test PUT request functionality
- [x] Style ProfileForm

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs and all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that all previous functionality still works without errors.
